language: cpp

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker

before_cache:
  - ./manage.sh save_images


stages:
  - tests_and_lints

jobs:
  include:
    - stage: tests_and_lints
      name: test
      script:
        - ./manage.sh test
        - ./manage.sh upload_codecov
    - stage: tests_and_lints
      name: lint
      script:
        - ./manage.sh lint
